### PR TITLE
[Fix] Color token presentation accessibility

### LINKED ISSUE #173: Fix Color-token presentation accessibility
## Expected Behavior or Possible Solution

Use `figure` and code-generated `svg`.
https://codepen.io/tigt/post/semantic-html-for-colors#are-you-kidding-me-safari-0

## Actual Behavior and Screenshots

https://github.com/vrk-kpa/suomifi-ui-components/blob/develop/src/core/Colors/Colors.tsx#L49

## Steps to Reproduce the Problem

https://vrk-kpa.github.io/suomifi-ui-components/#/Introduction/Colors

## Specifications

- Version: 0.2.6

### PR DESCRIPTION
**Pull request by ketsappi**
## Description

- Using `figure` and `svg` to show the color token
- Able to use keyboard to switch between color tokens with `Tab`-key
- Able to use keyboard to copy the key of currently selected color token with `Enter`-key
- Added snapshot test to see possible structure changes in the future

## Related Issue

Closes #173 

## Motivation and Context

Change increases accessibility of the colors by changing the semantics and adding support for keyboard actions.

## How Has This Been Tested?
- manually in the browser (macOS 10.15.1:  Firefox, Chrome, Safari, Opera)
- `yarn validate`

### CODE REVIEW

File: src/core/Colors/Colors.baseStyles.tsx [hunk 1]
```diff
@@ -17,20 +17,39 @@ export const baseStyles = withSuomifiTheme(
       flex-direction: column;
       justify-content: flex-end;
       float: left;
-      width: 192px;
-      height: 180px;
+      width: 208px;
```
Comment (aappoalander) [inline src/core/Colors/Colors.baseStyles.tsx]: Where do these magic numbers come from? Looks like these were just updated, but this kind of arbitrary looking styles based on absolute values would benefit from comments in my opinion. These are used with styleguidist?

File: src/core/Colors/Colors.baseStyles.tsx [hunk 2]
```diff
@@ -17,20 +17,39 @@ export const baseStyles = withSuomifiTheme(
...
         border-bottom-color: ${readableColor(color)};
       }
 
+      figcaption {
+        display: flex;
+        flex-direction: column;
+        justify-content: flex-end;
+        position: absolute;
+        left: 8px;
+        bottom: 8px;
```
Comment (aappoalander) [inline src/core/Colors/Colors.baseStyles.tsx]: Do we have design tokens that would suit this usecase?

Comment (ketsappi) [reply src/core/Colors/Colors.baseStyles.tsx]: You mean the `left` and `bottom` values?

Like this?
```scss
left: ${theme.spacing.s};
bottom: ${theme.spacing.s};
```

Comment (aappoalander) [reply src/core/Colors/Colors.baseStyles.tsx]: Yes, not sure if it's relevant here, but I like this better since those are defined.

Comment (ketsappi) [reply src/core/Colors/Colors.baseStyles.tsx]: This change was made and committed.

File: src/core/Colors/Colors.baseStyles.tsx (hunk 1 above)
Comment (ketsappi) [reply src/core/Colors/Colors.baseStyles.tsx]: These values for `width` and `height` was updated to keep the visual presentation, in the styleguidist, like it was previously; looking square.

Possibly later this could be done dynamically based on available size, but at this point this it not worth the effort.

Comment (LJKaski) [reply src/core/Colors/Colors.baseStyles.tsx]: If something was done regarding the visual presentation, I think a screenshot or two would make the review a lot easier, even if they are just to show that things stayed the same, like in this case.

Comment (ketsappi) [reply src/core/Colors/Colors.baseStyles.tsx]: I didn't add any screenshots for the PR as there were no visual changes needed to be done with this fix. And change to these values here were done only to keep the same appearance as before.

But if there will be later changes that will change the color tokens presentation to be more dynamic, screenshots would be very much needed to show the difference eg. in some example cases (_different browser width_).
